rails_testframework/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users
root 'users#index'
end

rails_testframework/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_testframework/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

rails_testframework/app/models/user.rb
class User < ApplicationRecord
  validates :username, :uniqueness => true
  has_many :posts

  def post_count
    posts.count
  end
end

rails_testframework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_testframework/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

rails_testframework/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_testframework/app/helpers/users_helper.rb
module UsersHelper
end

rails_testframework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestframework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_testframework/app/views/users/index.html.erb
<% @users.each do |u|%>
  <%=link_to u.username, user_path(u) %>
  <br>
<%end%>

<%= link_to "Create a new user", new_user_path %>

rails_testframework/app/views/users/new.html.erb
<%= form_for @user do |user| %>
  <%= user.label :username %>
  <%= user.text_field :username %> 
  <%= user.submit %>
<%end%>

rails_testframework/app/views/users/show.html.erb
<%= @user.username %>